sudo: false
language: ruby
cache: bundler
dist: xenial

services:
  - mysql
  - postgresql

addons:
  postgresql: 10
  apt:
    packages:
    - postgresql-10-postgis-2.4

before_install:
  - gem install bundler

before_script:
  - mysql -e 'create database makara_test;'
  - psql -c 'create database makara_test;' -U postgres
  - psql -c 'create extension postgis;' -U postgres

rvm:
  - 2.5
  - 2.6
  - 2.7
  - 3.0
  - ruby-head
  - jruby

gemfile:
  - gemfiles/ar52.gemfile
  - gemfiles/ar60.gemfile
  - gemfiles/ar61.gemfile
  - gemfiles/ar-head.gemfile

env:
  global:
    - "JRUBY_OPTS='--dev -J-Xmx1024M'"

matrix:
  exclude:
    - gemfile: gemfiles/ar52.gemfile
      rvm: 3.0
    - gemfile: gemfiles/ar52.gemfile
      rvm: ruby-head
  allow_failures:
    - gemfile: gemfiles/ar-head.gemfile
    - rvm: ruby-head
    - rvm: jruby
    - rvm: 3.0
  fast_finish: true
